spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password1234
#  batch:
#    jdbc:
#      initialize-schema: ALWAYS

